/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.wordpress.gestaoconsultamedica.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import com.wordpress.gestaoconsultamedica.model.Consulta;
import com.wordpress.gestaoconsultamedica.model.ModelApiResponse;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-02-07T13:33:43.748Z")

@Api(value = "consulta", description = "the consulta API")
public interface ConsultaApi {

    @ApiOperation(value = "Cadastra nova consulta", notes = "", response = Consulta.class, tags={ "Consulta", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = Consulta.class),
        @ApiResponse(code = 404, message = "Not Found", response = ModelApiResponse.class),
        @ApiResponse(code = 405, message = "Error operation", response = ModelApiResponse.class) })
    
    @RequestMapping(value = "/consulta",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Consulta> cadastro(@ApiParam(value = "Informacoes sobre a consulta" ,required=true )  @Valid @RequestBody Consulta body);


    @ApiOperation(value = "Resgata consulta pelo codigo", notes = ".\"", response = Consulta.class, tags={ "Consulta", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Consulta.class),
        @ApiResponse(code = 404, message = "Not Found", response = ModelApiResponse.class),
        @ApiResponse(code = 405, message = "Error operation", response = ModelApiResponse.class) })
    
    @RequestMapping(value = "/consulta/{codigo}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Consulta> consultaPorCodigo(@ApiParam(value = "Codigo da consulta para busca",required=true ) @PathVariable("codigo") Long codigo);


    @ApiOperation(value = "Excluir consulta agendada", notes = "", response = ModelApiResponse.class, tags={ "Consulta", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation", response = ModelApiResponse.class),
        @ApiResponse(code = 404, message = "Not Found", response = ModelApiResponse.class),
        @ApiResponse(code = 405, message = "Error operation", response = ModelApiResponse.class) })
    
    @RequestMapping(value = "/consulta/{codigo}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<ModelApiResponse> delete(@ApiParam(value = "Codigo da consulta para exclusao",required=true ) @PathVariable("codigo") Long codigo);


    @ApiOperation(value = "Altera consulta existente", notes = "", response = Consulta.class, tags={ "Consulta", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation", response = Consulta.class),
        @ApiResponse(code = 404, message = "Not Found", response = ModelApiResponse.class),
        @ApiResponse(code = 405, message = "Error operation", response = ModelApiResponse.class) })
    
    @RequestMapping(value = "/consulta",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Consulta> update(@ApiParam(value = "Informacoes sobre a consulta para efeturar a alteracao" ,required=true )  @Valid @RequestBody Consulta body);

}
